name: Go Module Auto Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Fetch tags
        run: |
          git fetch --force --tags
          echo "Tags in repo:"
          git tag -l

      - name: Compute next version
        id: ver
        shell: bash
        run: |
          # Find latest v* tag by semantic sort
          LAST_TAG=$(git tag --list "v*" --sort=-v:refname | head -n1)
          if [ -z "$LAST_TAG" ]; then
            LAST_TAG="v1.0.0"
          fi
          echo "Last tag: $LAST_TAG"

          CORE=${LAST_TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<<"$CORE"
          NEW_TAG="v${MAJOR}.${MINOR}.$((PATCH+1))"
          echo "New tag: $NEW_TAG"

          echo "new_tag=$NEW_TAG" >> "$GITHUB_OUTPUT"

      - name: Ensure authenticated push
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Create and push tag
        run: |
          git tag ${{ steps.ver.outputs.new_tag }}
          git push origin ${{ steps.ver.outputs.new_tag }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.ver.outputs.new_tag }}
          name: ${{ steps.ver.outputs.new_tag }}
          body: "Automated release for Go module."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
